[project]
name = "sentinel-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "msteckle", email = "morganrsteckler@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "affine>=2.4.0",
    "asf-search>=12.0.7",
    "folium>=0.20.0",
    "geopandas>=1.1.1",
    "lxml>=6.0.2",
    "matplotlib>=3.10.8",
    "numpy>=2.0.0",
    "openeo>=0.49.0",
    "pandas>=2.3.3",
    "phidown>=0.1.25",
    "pystac-client>=0.8.6",
    "pyarrow>=23.0.1",
    "pydantic>=2.12.0",
    "pyproj>=3.7.0",
    "pyyaml>=6.0.3",
    "rasterio>=1.5.2",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "s5cmd>=0.3.3",
    "shapely>=2.1.2",
    "typer>=0.20.0",
]

[project.optional-dependencies]
processing = [
    "dask[distributed]>=2025.9.0",
    "rasterio>=1.4.4",
    "xarray>=2025.1.1",
]
hpc = [
    "dask-jobqueue>=0.9.0",
]

[project.scripts]
sentinel-py = "sentinel_py.cli.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "pytest>=9.1.1",
    "uv>=0.11.7",
]
